/**
 * BuildingType enum — pure value enum with no dependencies.
 * Extracted to its own file to allow import from game-data module without circular deps.
 */

export enum BuildingType {
    WoodcutterHut = 1,
    StorageArea = 2,
    Sawmill = 3,
    StonecutterHut = 4,
    GrainFarm = 5,
    Mill = 6,
    Bakery = 7,
    FisherHut = 8,
    AnimalRanch = 9,
    Slaughterhouse = 10,
    WaterworkHut = 11,
    CoalMine = 12,
    IronMine = 13,
    GoldMine = 14,
    IronSmelter = 15,
    SmeltGold = 16,
    WeaponSmith = 17,
    ToolSmith = 18,
    Barrack = 19,
    ForesterHut = 20,
    HealerHut = 21,
    GuardTowerSmall = 22,
    HunterHut = 24,
    DonkeyRanch = 25,
    StoneMine = 26,
    SulfurMine = 27,
    ResidenceSmall = 29,
    ResidenceMedium = 30,
    ResidenceBig = 31,
    GuardTowerBig = 32,
    Castle = 33,
    AmmunitionMaker = 34,
    SmallTemple = 35,
    LargeTemple = 36,
    LookoutTower = 37,
    Shipyard = 38,
    Eyecatcher01 = 39,
    Vinyard = 40,
    SiegeWorkshop = 41,
    Eyecatcher02 = 42,
    // Eyecatchers 03-12: race-specific decorative monuments
    Eyecatcher03 = 43,
    Eyecatcher04 = 44,
    Eyecatcher05 = 45,
    Eyecatcher06 = 46,
    Eyecatcher07 = 47,
    Eyecatcher08 = 48,
    Eyecatcher09 = 49,
    Eyecatcher10 = 50,
    Eyecatcher11 = 51,
    Eyecatcher12 = 52,
    // Race-specific drink production buildings
    AgaveFarmerHut = 53,
    TequilaMakerHut = 54,
    BeekeeperHut = 55,
    MeadMakerHut = 56,
    SunflowerFarmerHut = 57,
    SunflowerOilMakerHut = 58,
    MushroomFarm = 59,
    DarkTemple = 60,
    Fortress = 61,
    ManaCopterHall = 62,
}
