/**
 * JIL frame offset corrections — fixes mispositioned frames in original game art.
 *
 * Some animation frames have their pixel content displaced within the canvas
 * (the image header offset is correct, but the pixels are shifted).
 * This module declares per-frame pixel corrections to apply at load time.
 *
 * Auto-generated by: npx tsx scripts/generate-frame-corrections.ts
 *
 * @module renderer/sprite-metadata/jil-frame-corrections
 */

import { SETTLER_JOB_INDICES } from './jil-indices';

/** A pixel-level offset correction for a single animation frame. */
export interface FrameCorrection {
    /** 0-based frame index within the direction */
    frame: number;
    /** Horizontal pixel shift to apply (positive = move right) */
    dx: number;
    /** Vertical pixel shift to apply (positive = move down) */
    dy: number;
}

/** Corrections for a specific direction within a job. */
export interface DirectionCorrection {
    /** DIL direction index (0=SE, 1=E, 2=SW, 3=NW, 4=W, 5=NE for 6-dir units) */
    direction: number;
    /** Per-frame corrections */
    frames: readonly FrameCorrection[];
}

/** Roman (20.jil) */
export const FRAME_CORRECTIONS_20: ReadonlyMap<number, readonly DirectionCorrection[]> = new Map([
    [27, [ // unmapped job
        { direction: 0, /* SE */ frames: [
            { frame: 12, dx: 18, dy: -1 },
        ] },
    ]],
    [30, [ // unmapped job
        { direction: 3, /* NW */ frames: [
            { frame: 4, dx: -17, dy: -2 },
        ] },
    ]],
    [32, [ // unmapped job
        { direction: 3, /* NW */ frames: [
            { frame: 4, dx: -11, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.carrier.C_DOWN_NONE, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -9, dy: -4 },
            { frame: 3, dx: -9, dy: -5 },
            { frame: 4, dx: -9, dy: -4 },
            { frame: 5, dx: -9, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.carrier.C_IDLE2, [
        { direction: 5, /* NE */ frames: [
            { frame: 3, dx: -8, dy: -3 },
            { frame: 25, dx: -8, dy: -2 },
            { frame: 26, dx: -8, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.carrier.C_IDLE3, [
        { direction: 0, /* SE */ frames: [
            { frame: 19, dx: -8, dy: -3 },
        ] },
        { direction: 2, /* SW */ frames: [
            { frame: 4, dx: 15, dy: -1 },
            { frame: 5, dx: 15, dy: -1 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 19, dx: -8, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.digger.D_WORK, [
        { direction: 2, /* SW */ frames: [
            { frame: 10, dx: -36, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.builder.B_WALK, [
        { direction: 5, /* NE */ frames: [
            { frame: 11, dx: 18, dy: -1 },
            { frame: 12, dx: 18, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.builder.B_WORK, [
        { direction: 3, /* NW */ frames: [
            { frame: 2, dx: -14, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.woodcutter.WC_CUT_TREE, [
        { direction: 4, /* W */ frames: [
            { frame: 2, dx: 21, dy: 0 },
            { frame: 3, dx: 21, dy: 0 },
            { frame: 5, dx: -17, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.woodcutter.WC_PICKUP_LOG, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -11, dy: -4 },
            { frame: 3, dx: -11, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.stonecutter.ST_PICKUP, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: -17, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.forester.F_WALK_TREE, [
        { direction: 5, /* NE */ frames: [
            { frame: 5, dx: 9, dy: -3 },
            { frame: 6, dx: 9, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.forester.F_PLANT_SMALLTREE, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -7, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.farmer.FG_WALK_GRAIN, [
        { direction: 1, /* E */ frames: [
            { frame: 12, dx: 16, dy: -1 },
            { frame: 13, dx: 16, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.farmer.FG_SEED_PLANTS, [
        { direction: 1, /* E */ frames: [
            { frame: 7, dx: -20, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.farmer.FG_CUT_GRAIN, [
        { direction: 0, /* SE */ frames: [
            { frame: 5, dx: -24, dy: -2 },
            { frame: 6, dx: -25, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_WALK_GRAIN, [
        { direction: 0, /* SE */ frames: [
            { frame: 10, dx: 15, dy: -1 },
            { frame: 11, dx: 15, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_PICKUP_WATER, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -13, dy: -5 },
            { frame: 4, dx: -14, dy: -6 },
            { frame: 5, dx: -14, dy: -6 },
            { frame: 6, dx: -13, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_PICKUP_GRAIN, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -15, dy: -4 },
            { frame: 4, dx: -15, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_WALK_EMPTY_FOOD, [
        { direction: 5, /* NE */ frames: [
            { frame: 9, dx: 15, dy: -1 },
            { frame: 10, dx: 15, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_FEED, [
        { direction: 0, /* SE */ frames: [
            { frame: 7, dx: -19, dy: 1 },
            { frame: 8, dx: -18, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.fisher.FI_WALK_FISH, [
        { direction: 1, /* E */ frames: [
            { frame: 5, dx: 10, dy: 0 },
            { frame: 6, dx: 10, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.fisher.FI_CATCH_FISH, [
        { direction: 0, /* SE */ frames: [
            { frame: 5, dx: -58, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.fisher.FI_PICKUP_FISH, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -7, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.fisher.FI_THROW_ROD, [
        { direction: 0, /* SE */ frames: [
            { frame: 17, dx: -25, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.water_worker.W_WALK_EMPTY_WATER, [
        { direction: 1, /* E */ frames: [
            { frame: 10, dx: -10, dy: -1 },
        ] },
        { direction: 2, /* SW */ frames: [
            { frame: 12, dx: 12, dy: -3 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 4, dx: -8, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.water_worker.W_PICKUP_WATER, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -8, dy: -4 },
            { frame: 3, dx: -9, dy: -5 },
            { frame: 4, dx: -9, dy: -4 },
            { frame: 5, dx: -8, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.hunter.H_PICKUP_MEAT, [
        { direction: 5, /* NE */ frames: [
            { frame: 6, dx: 25, dy: -3 },
            { frame: 7, dx: 25, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sawmill_worker.SW_WALK_LOG, [
        { direction: 0, /* SE */ frames: [
            { frame: 8, dx: 14, dy: -1 },
            { frame: 9, dx: 14, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sawmill_worker.SW_PICKUP_LOG, [
        { direction: 0, /* SE */ frames: [
            { frame: 7, dx: -10, dy: 4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sawmill_worker.SW_PICKUP_BOARD, [
        { direction: 1, /* E */ frames: [
            { frame: 7, dx: -12, dy: 3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_WALK_IRONORE, [
        { direction: 5, /* NE */ frames: [
            { frame: 9, dx: 15, dy: -1 },
            { frame: 10, dx: 15, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_COAL, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -11, dy: -4 },
            { frame: 3, dx: -11, dy: -5 },
            { frame: 4, dx: -11, dy: -4 },
            { frame: 5, dx: -11, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_GOLDBAR, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -11, dy: -4 },
            { frame: 3, dx: -11, dy: -5 },
            { frame: 4, dx: -11, dy: -5 },
            { frame: 5, dx: -11, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_GOLDORE, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -11, dy: -4 },
            { frame: 3, dx: -11, dy: -5 },
            { frame: 4, dx: -11, dy: -4 },
            { frame: 5, dx: -11, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_IRONBAR, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -11, dy: -4 },
            { frame: 3, dx: -11, dy: -5 },
            { frame: 4, dx: -11, dy: -5 },
            { frame: 5, dx: -11, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_WORK, [
        { direction: 0, /* SE */ frames: [
            { frame: 5, dx: -15, dy: -3 },
            { frame: 6, dx: -15, dy: -3 },
            { frame: 7, dx: -15, dy: -3 },
            { frame: 8, dx: -15, dy: -3 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 4, dx: 18, dy: 1 },
            { frame: 5, dx: 18, dy: 3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_IRONORE, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -11, dy: -4 },
            { frame: 3, dx: -11, dy: -5 },
            { frame: 4, dx: -11, dy: -4 },
            { frame: 5, dx: -11, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smith.S_WALK_IRONBAR, [
        { direction: 3, /* NW */ frames: [
            { frame: 5, dx: -14, dy: -2 },
            { frame: 6, dx: -14, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smith.S_PICKUP_COAL, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -9, dy: -4 },
        ] },
        { direction: 1, /* E */ frames: [
            { frame: 1, dx: 32, dy: -7 },
            { frame: 2, dx: 32, dy: -7 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smith.S_PICKUP_IRONBAR, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -9, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.miller.MI_WALK_GRAIN, [
        { direction: 3, /* NW */ frames: [
            { frame: 4, dx: 10, dy: -1 },
            { frame: 5, dx: 10, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.miller.MI_PICKUP_GRAIN, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -12, dy: -3 },
            { frame: 3, dx: -12, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.miller.MI_PICKUP_FLOUR, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -12, dy: -3 },
            { frame: 3, dx: -12, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_WALK, [
        { direction: 3, /* NW */ frames: [
            { frame: 8, dx: 9, dy: -2 },
            { frame: 9, dx: 9, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_WALK_SHOVEL, [
        { direction: 5, /* NE */ frames: [
            { frame: 4, dx: -16, dy: -2 },
            { frame: 5, dx: -16, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_WORK_DOUGH, [
        { direction: 1, /* E */ frames: [
            { frame: 7, dx: 46, dy: -2 },
            { frame: 8, dx: 46, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_PICKUP_WATER, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -18, dy: -6 },
            { frame: 4, dx: -17, dy: -7 },
            { frame: 5, dx: -17, dy: -7 },
            { frame: 6, dx: -18, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_PICKUP_FLOUR, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -19, dy: -5 },
            { frame: 4, dx: -18, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.butcher.BU_WALK, [
        { direction: 5, /* NE */ frames: [
            { frame: 6, dx: 19, dy: -3 },
            { frame: 7, dx: 19, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.butcher.BU_PICKUP_ANIMAL, [
        { direction: 4, /* W */ frames: [
            { frame: 3, dx: 24, dy: 0 },
            { frame: 4, dx: 24, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.unknown_worker.VM_PICKUP_BOARD, [
        { direction: 1, /* E */ frames: [
            { frame: 4, dx: 31, dy: -13 },
            { frame: 5, dx: 31, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.healer.HE_CONJURE, [
        { direction: 0, /* SE */ frames: [
            { frame: 5, dx: 29, dy: -1 },
            { frame: 6, dx: 29, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.ammunition_maker.AM_PICKUP_FIRSTGOOD, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -18, dy: -4 },
            { frame: 4, dx: -18, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.ammunition_maker.AM_PICKUP_AMMO, [
        { direction: 4, /* W */ frames: [
            { frame: 3, dx: -12, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_WORK, [
        { direction: 3, /* NW */ frames: [
            { frame: 2, dx: -16, dy: -2 },
            { frame: 5, dx: -16, dy: -4 },
            { frame: 6, dx: -16, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_PICKUP_IRONBAR, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -16, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_PICKUP_BOARD, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -16, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_PICKUP_IRONBAR2, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -16, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.wine_maker.V_WALK, [
        { direction: 5, /* NE */ frames: [
            { frame: 10, dx: 11, dy: -4 },
            { frame: 11, dx: 11, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.wine_maker.V_WORK_PLANT, [
        { direction: 3, /* NW */ frames: [
            { frame: 5, dx: 19, dy: -2 },
            { frame: 6, dx: 19, dy: 1 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 9, dx: -12, dy: 2 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 8, dx: -10, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.wine_maker.V_PICKUP_WINE, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -14, dy: -5 },
            { frame: 4, dx: -13, dy: -6 },
            { frame: 5, dx: -13, dy: -7 },
            { frame: 6, dx: -13, dy: -6 },
        ] },
    ]],
    [229, [ // unmapped job
        { direction: 0, /* SE */ frames: [
            { frame: 9, dx: 22, dy: -4 },
            { frame: 10, dx: 22, dy: -1 },
        ] },
    ]],
    [232, [ // unmapped job
        { direction: 2, /* SW */ frames: [
            { frame: 5, dx: -12, dy: -5 },
            { frame: 6, dx: -12, dy: -1 },
        ] },
    ]],
    [235, [ // unmapped job
        { direction: 4, /* W */ frames: [
            { frame: 1, dx: -13, dy: -2 },
            { frame: 2, dx: -13, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_1.BML01_STOW_BOW, [
        { direction: 4, /* W */ frames: [
            { frame: 1, dx: -27, dy: -1 },
            { frame: 2, dx: -27, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_1.BML01_THROW_STONE, [
        { direction: 0, /* SE */ frames: [
            { frame: 14, dx: -13, dy: 0 },
        ] },
    ]],
    [241, [ // unmapped job
        { direction: 1, /* E */ frames: [
            { frame: 6, dx: -14, dy: -2 },
            { frame: 7, dx: -14, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_2.BML02_SHOOT, [
        { direction: 5, /* NE */ frames: [
            { frame: 19, dx: 40, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_2.BML02_THROW_STONE, [
        { direction: 1, /* E */ frames: [
            { frame: 3, dx: -21, dy: -4 },
            { frame: 4, dx: -21, dy: -6 },
            { frame: 6, dx: -21, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_2.BML02_FIGHT, [
        { direction: 4, /* W */ frames: [
            { frame: 5, dx: -15, dy: -2 },
            { frame: 11, dx: 26, dy: -2 },
            { frame: 12, dx: 26, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_3.BML03_STOW_BOW, [
        { direction: 5, /* NE */ frames: [
            { frame: 3, dx: 21, dy: -2 },
            { frame: 4, dx: 21, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_3.BML03_THROW_STONE, [
        { direction: 1, /* E */ frames: [
            { frame: 2, dx: -19, dy: -3 },
            { frame: 3, dx: -19, dy: -5 },
            { frame: 4, dx: -19, dy: -6 },
            { frame: 5, dx: -19, dy: -7 },
            { frame: 6, dx: -19, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.specialist_1.MEL01_FIGHT, [
        { direction: 4, /* W */ frames: [
            { frame: 5, dx: 33, dy: -2 },
            { frame: 6, dx: 33, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.specialist_2.MEL02_HEAL, [
        { direction: 3, /* NW */ frames: [
            { frame: 4, dx: -29, dy: -2 },
            { frame: 5, dx: -29, dy: 3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.priest.PR_CASTSPELL, [
        { direction: 2, /* SW */ frames: [
            { frame: 20, dx: -28, dy: 28 },
        ] },
        { direction: 3, /* NW */ frames: [
            { frame: 20, dx: -27, dy: 26 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 20, dx: -28, dy: 23 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.saboteur.SA_WORK_3, [
        { direction: 0, /* SE */ frames: [
            { frame: 11, dx: -20, dy: 2 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 3, dx: -23, dy: -4 },
            { frame: 4, dx: -23, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.saboteur.SA_WORK_4, [
        { direction: 0, /* SE */ frames: [
            { frame: 21, dx: -16, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.saboteur.SA_WORK_5, [
        { direction: 4, /* W */ frames: [
            { frame: 6, dx: -19, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.saboteur.SA_WORK_6, [
        { direction: 0, /* SE */ frames: [
            { frame: 1, dx: 24, dy: -3 },
            { frame: 2, dx: 24, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.pioneer.P_SHOVEL, [
        { direction: 1, /* E */ frames: [
            { frame: 5, dx: 35, dy: -7 },
            { frame: 6, dx: 35, dy: -1 },
        ] },
        { direction: 2, /* SW */ frames: [
            { frame: 10, dx: -36, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.pioneer.P_WORK, [
        { direction: 0, /* SE */ frames: [
            { frame: 5, dx: -9, dy: -4 },
            { frame: 6, dx: -10, dy: -5 },
            { frame: 7, dx: -10, dy: -5 },
            { frame: 8, dx: -10, dy: -5 },
            { frame: 9, dx: -10, dy: -5 },
            { frame: 10, dx: -10, dy: -5 },
            { frame: 11, dx: -10, dy: -4 },
            { frame: 12, dx: -10, dy: -5 },
            { frame: 13, dx: -10, dy: -5 },
            { frame: 14, dx: -10, dy: -5 },
            { frame: 15, dx: -10, dy: -6 },
            { frame: 16, dx: -10, dy: -6 },
            { frame: 17, dx: -10, dy: -6 },
            { frame: 18, dx: -10, dy: -6 },
            { frame: 19, dx: -10, dy: -5 },
            { frame: 20, dx: -10, dy: -4 },
            { frame: 21, dx: -9, dy: -3 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 14, dx: -8, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.thief.TH_WALK, [
        { direction: 3, /* NW */ frames: [
            { frame: 12, dx: 11, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.thief.TH_DROP_GOOD, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -7, dy: -4 },
            { frame: 4, dx: -7, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.geologist.G_WORK, [
        { direction: 3, /* NW */ frames: [
            { frame: 22, dx: -18, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.gardener.GA_WORK, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: 38, dy: -7 },
            { frame: 4, dx: 38, dy: -3 },
        ] },
        { direction: 2, /* SW */ frames: [
            { frame: 11, dx: -38, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.gardener.GA_BEAT_MUSHROOM, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: -19, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.temple_servant.TS_WALK_WINE, [
        { direction: 4, /* W */ frames: [
            { frame: 3, dx: 14, dy: -3 },
            { frame: 4, dx: 14, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.temple_servant.TS_PICKUP_WINE, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -22, dy: -6 },
            { frame: 4, dx: -22, dy: -9 },
            { frame: 5, dx: -22, dy: -8 },
            { frame: 6, dx: -22, dy: -7 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.angel_3.ANGEL3_WALK, [
        { direction: 2, /* SW */ frames: [
            { frame: 9, dx: -2, dy: 89 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.donkey.DONKEY_WALK, [
        { direction: 4, /* W */ frames: [
            { frame: 7, dx: -23, dy: -2 },
            { frame: 8, dx: -23, dy: 2 },
        ] },
    ]],
]);

/** Viking (21.jil) */
export const FRAME_CORRECTIONS_21: ReadonlyMap<number, readonly DirectionCorrection[]> = new Map([
    [11, [ // unmapped job
        { direction: 1, /* E */ frames: [
            { frame: 1, dx: -8, dy: -3 },
        ] },
    ]],
    [14, [ // unmapped job
        { direction: 2, /* SW */ frames: [
            { frame: 10, dx: -13, dy: -5 },
        ] },
    ]],
    [27, [ // unmapped job
        { direction: 3, /* NW */ frames: [
            { frame: 7, dx: -9, dy: -3 },
        ] },
    ]],
    [30, [ // unmapped job
        { direction: 5, /* NE */ frames: [
            { frame: 10, dx: -9, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.carrier.C_DOWN_NONE, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -13, dy: -3 },
            { frame: 3, dx: -13, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.carrier.C_IDLE1, [
        { direction: 0, /* SE */ frames: [
            { frame: 25, dx: -12, dy: -5 },
            { frame: 26, dx: -12, dy: -5 },
        ] },
        { direction: 1, /* E */ frames: [
            { frame: 7, dx: -12, dy: 0 },
        ] },
        { direction: 3, /* NW */ frames: [
            { frame: 17, dx: -10, dy: -8 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.carrier.C_IDLE2, [
        { direction: 0, /* SE */ frames: [
            { frame: 18, dx: -18, dy: -2 },
            { frame: 19, dx: -18, dy: -2 },
            { frame: 21, dx: -19, dy: -2 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 25, dx: -21, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.carrier.C_STRIKE1, [
        { direction: 1, /* E */ frames: [
            { frame: 13, dx: -24, dy: 3 },
            { frame: 14, dx: -24, dy: 7 },
        ] },
        { direction: 3, /* NW */ frames: [
            { frame: 13, dx: -24, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.digger.D_WORK, [
        { direction: 2, /* SW */ frames: [
            { frame: 10, dx: -32, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.builder.B_WORK, [
        { direction: 3, /* NW */ frames: [
            { frame: 2, dx: -18, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.woodcutter.WC_WALK, [
        { direction: 4, /* W */ frames: [
            { frame: 10, dx: 13, dy: -2 },
            { frame: 11, dx: 13, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.woodcutter.WC_PICKUP_LOG, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -10, dy: -3 },
            { frame: 3, dx: -10, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.stonecutter.ST_WALK, [
        { direction: 3, /* NW */ frames: [
            { frame: 3, dx: 8, dy: -2 },
            { frame: 4, dx: 8, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.stonecutter.ST_HACK, [
        { direction: 5, /* NE */ frames: [
            { frame: 6, dx: -17, dy: 4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.stonecutter.ST_PICKUP, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -19, dy: -4 },
            { frame: 4, dx: -19, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.forester.F_WALK, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: 12, dy: -2 },
            { frame: 5, dx: 12, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.forester.F_PLANT_SMALLTREE, [
        { direction: 4, /* W */ frames: [
            { frame: 8, dx: -16, dy: -4 },
            { frame: 9, dx: -16, dy: -3 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 18, dx: -11, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.farmer.FG_SEED_PLANTS, [
        { direction: 1, /* E */ frames: [
            { frame: 7, dx: -15, dy: -2 },
            { frame: 8, dx: -16, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.farmer.FG_CUT_GRAIN, [
        { direction: 0, /* SE */ frames: [
            { frame: 5, dx: -22, dy: -1 },
            { frame: 6, dx: -22, dy: -2 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 6, dx: -22, dy: -1 },
        ] },
    ]],
    [71, [ // unmapped job
        { direction: 1, /* E */ frames: [
            { frame: 3, dx: 32, dy: -1 },
            { frame: 4, dx: 32, dy: 0 },
        ] },
        { direction: 3, /* NW */ frames: [
            { frame: 11, dx: -19, dy: -7 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_WALK_GRAIN, [
        { direction: 1, /* E */ frames: [
            { frame: 12, dx: -15, dy: -2 },
            { frame: 13, dx: -15, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_PICKUP_WATER, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -15, dy: -3 },
            { frame: 4, dx: -15, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_PICKUP_GRAIN, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -10, dy: -2 },
            { frame: 3, dx: -10, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_WALK_FULL_FOOD, [
        { direction: 1, /* E */ frames: [
            { frame: 5, dx: 11, dy: 0 },
            { frame: 6, dx: 11, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_FEED, [
        { direction: 0, /* SE */ frames: [
            { frame: 7, dx: -16, dy: 0 },
            { frame: 8, dx: -16, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.fisher.FI_WALK_FISH, [
        { direction: 3, /* NW */ frames: [
            { frame: 1, dx: -9, dy: -1 },
            { frame: 2, dx: -9, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.fisher.FI_PICKUP_FISH, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -9, dy: -3 },
            { frame: 4, dx: -9, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.water_worker.W_WALK_EMPTY_WATER, [
        { direction: 0, /* SE */ frames: [
            { frame: 10, dx: -12, dy: -2 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 4, dx: -11, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.water_worker.W_WALK_FULL_WATER, [
        { direction: 2, /* SW */ frames: [
            { frame: 10, dx: 10, dy: -2 },
            { frame: 11, dx: 10, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.water_worker.W_PICKUP_WATER, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -10, dy: -3 },
            { frame: 3, dx: -10, dy: -4 },
            { frame: 4, dx: -10, dy: -4 },
            { frame: 5, dx: -10, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.hunter.H_WALK, [
        { direction: 1, /* E */ frames: [
            { frame: 3, dx: -14, dy: 0 },
            { frame: 4, dx: -14, dy: 1 },
        ] },
        { direction: 3, /* NW */ frames: [
            { frame: 11, dx: -10, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.hunter.H_PICKUP_MEAT, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -8, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sawmill_worker.SW_WALK_BOARD, [
        { direction: 3, /* NW */ frames: [
            { frame: 9, dx: 8, dy: -1 },
            { frame: 10, dx: 8, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sawmill_worker.SW_WORK, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: -18, dy: -7 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sawmill_worker.SW_PICKUP_LOG, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -8, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sawmill_worker.SW_PICKUP_BOARD, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -8, dy: -4 },
        ] },
        { direction: 1, /* E */ frames: [
            { frame: 7, dx: -11, dy: 3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_WALK, [
        { direction: 4, /* W */ frames: [
            { frame: 6, dx: 11, dy: -2 },
            { frame: 7, dx: 11, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_WALK_COAL, [
        { direction: 1, /* E */ frames: [
            { frame: 1, dx: -8, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_COAL, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -10, dy: -4 },
            { frame: 4, dx: -10, dy: -3 },
            { frame: 5, dx: -10, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_GOLDBAR, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -10, dy: -3 },
            { frame: 3, dx: -10, dy: -4 },
            { frame: 4, dx: -10, dy: -3 },
            { frame: 5, dx: -10, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_GOLDORE, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -10, dy: -3 },
            { frame: 3, dx: -10, dy: -4 },
            { frame: 4, dx: -10, dy: -3 },
            { frame: 5, dx: -10, dy: -3 },
            { frame: 6, dx: 19, dy: -3 },
            { frame: 7, dx: 19, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_IRONBAR, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -10, dy: -3 },
            { frame: 3, dx: -10, dy: -4 },
            { frame: 4, dx: -10, dy: -3 },
            { frame: 5, dx: -10, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_WORK, [
        { direction: 0, /* SE */ frames: [
            { frame: 6, dx: -13, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_IRONORE, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -10, dy: -3 },
            { frame: 3, dx: -10, dy: -4 },
            { frame: 4, dx: -10, dy: -3 },
            { frame: 5, dx: -10, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.miner.M_WALK, [
        { direction: 2, /* SW */ frames: [
            { frame: 8, dx: -10, dy: -1 },
            { frame: 9, dx: -10, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smith.S_WALK, [
        { direction: 4, /* W */ frames: [
            { frame: 12, dx: 11, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smith.S_WALK_STEEL, [
        { direction: 4, /* W */ frames: [
            { frame: 8, dx: -37, dy: 0 },
            { frame: 9, dx: -37, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smith.S_WORK, [
        { direction: 1, /* E */ frames: [
            { frame: 6, dx: -10, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smith.S_PICKUP_IRONBAR, [
        { direction: 5, /* NE */ frames: [
            { frame: 2, dx: 27, dy: -2 },
            { frame: 3, dx: 27, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smith.S_PICKUP_STEEL, [
        { direction: 3, /* NW */ frames: [
            { frame: 4, dx: -13, dy: -7 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.miller.MI_WALK_FLOUR, [
        { direction: 3, /* NW */ frames: [
            { frame: 7, dx: 10, dy: -2 },
            { frame: 8, dx: 10, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.miller.MI_PICKUP_GRAIN, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -16, dy: -5 },
            { frame: 3, dx: -15, dy: -3 },
            { frame: 4, dx: -15, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.miller.MI_PICKUP_FLOUR, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -11, dy: -2 },
            { frame: 3, dx: -11, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_WALK_FLOUR, [
        { direction: 3, /* NW */ frames: [
            { frame: 11, dx: 8, dy: -3 },
            { frame: 12, dx: 8, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_WALK_DOUGH, [
        { direction: 5, /* NE */ frames: [
            { frame: 2, dx: 33, dy: -2 },
            { frame: 3, dx: 33, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_WORK_BREAD, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -11, dy: -4 },
            { frame: 4, dx: -11, dy: -4 },
            { frame: 5, dx: -11, dy: -4 },
            { frame: 6, dx: -12, dy: -4 },
            { frame: 7, dx: -11, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_WORK_DOUGH, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -11, dy: -4 },
            { frame: 4, dx: -11, dy: -4 },
            { frame: 5, dx: -11, dy: -4 },
            { frame: 6, dx: -12, dy: -4 },
            { frame: 7, dx: -11, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_PICKUP_WATER, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -16, dy: -4 },
            { frame: 4, dx: -15, dy: -5 },
            { frame: 5, dx: -16, dy: -5 },
            { frame: 6, dx: -16, dy: -4 },
        ] },
        { direction: 1, /* E */ frames: [
            { frame: 5, dx: -14, dy: -11 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_PICKUP_FLOUR, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -17, dy: -4 },
            { frame: 4, dx: -16, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.butcher.BU_WALK_MEAT, [
        { direction: 4, /* W */ frames: [
            { frame: 2, dx: -11, dy: -2 },
            { frame: 3, dx: -11, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.unknown_worker.VM_WALK, [
        { direction: 4, /* W */ frames: [
            { frame: 2, dx: 12, dy: -3 },
            { frame: 3, dx: 11, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.unknown_worker.VM_WALK_BOARD, [
        { direction: 0, /* SE */ frames: [
            { frame: 10, dx: -11, dy: -1 },
        ] },
        { direction: 2, /* SW */ frames: [
            { frame: 8, dx: -10, dy: 0 },
            { frame: 9, dx: -10, dy: -1 },
            { frame: 10, dx: -10, dy: -1 },
            { frame: 11, dx: -10, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.unknown_worker.VM_PICKUP_BOARD, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -13, dy: -4 },
        ] },
        { direction: 2, /* SW */ frames: [
            { frame: 7, dx: -17, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.unknown_worker.VM_PICKUP_IRONBAR, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -13, dy: -4 },
        ] },
        { direction: 2, /* SW */ frames: [
            { frame: 4, dx: -18, dy: -11 },
            { frame: 5, dx: -18, dy: -8 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.healer.HE_CONJURE, [
        { direction: 3, /* NW */ frames: [
            { frame: 8, dx: -29, dy: -1 },
            { frame: 9, dx: -29, dy: 2 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 6, dx: -26, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.charcoal_burner.CO_PICKUP_LOG, [
        { direction: 0, /* SE */ frames: [
            { frame: 6, dx: -21, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_WALK_IRONBAR, [
        { direction: 3, /* NW */ frames: [
            { frame: 7, dx: 10, dy: -4 },
            { frame: 8, dx: 10, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_WALK_IRONBAR2, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -11, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_WORK, [
        { direction: 3, /* NW */ frames: [
            { frame: 2, dx: -16, dy: -2 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 8, dx: 18, dy: 0 },
            { frame: 9, dx: 18, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_PICKUP_IRONBAR, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -13, dy: -2 },
            { frame: 3, dx: -14, dy: -3 },
            { frame: 4, dx: -13, dy: -4 },
        ] },
        { direction: 3, /* NW */ frames: [
            { frame: 3, dx: -17, dy: -8 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_PICKUP_BOARD, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -13, dy: -2 },
            { frame: 3, dx: -14, dy: -3 },
            { frame: 4, dx: -13, dy: -4 },
        ] },
        { direction: 2, /* SW */ frames: [
            { frame: 7, dx: -16, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_PICKUP_IRONBAR2, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -13, dy: -2 },
            { frame: 3, dx: -14, dy: -3 },
            { frame: 4, dx: -13, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.beekeeper.BK_WALK_BEEHIVE, [
        { direction: 3, /* NW */ frames: [
            { frame: 10, dx: -13, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.beekeeper.BK_PICKUP_HONEY, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -9, dy: -3 },
            { frame: 3, dx: -9, dy: -4 },
            { frame: 4, dx: -9, dy: -4 },
            { frame: 5, dx: -8, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.beekeeper.BK_WORK_2, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: -7, dy: -4 },
            { frame: 5, dx: -7, dy: -4 },
            { frame: 6, dx: -7, dy: -4 },
            { frame: 7, dx: -7, dy: -4 },
            { frame: 8, dx: -7, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.mead_maker.MM_PICKUP_HONEY, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -10, dy: -3 },
            { frame: 3, dx: -10, dy: -3 },
            { frame: 4, dx: -10, dy: -3 },
            { frame: 5, dx: -9, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.mead_maker.MM_PICKUP_MEAD, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -22, dy: 0 },
            { frame: 3, dx: -22, dy: -1 },
            { frame: 4, dx: -22, dy: -1 },
            { frame: 5, dx: -22, dy: 0 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 2, dx: -14, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.mead_maker.MM_PICKUP_WATER, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -10, dy: -3 },
            { frame: 3, dx: -10, dy: -3 },
            { frame: 4, dx: -10, dy: -4 },
            { frame: 5, dx: -10, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.swordsman_1.SML01_FIGHT, [
        { direction: 5, /* NE */ frames: [
            { frame: 12, dx: 26, dy: -2 },
            { frame: 13, dx: 26, dy: 1 },
        ] },
    ]],
    [229, [ // unmapped job
        { direction: 2, /* SW */ frames: [
            { frame: 6, dx: -16, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.swordsman_3.SML03_WALK, [
        { direction: 1, /* E */ frames: [
            { frame: 7, dx: 25, dy: -2 },
            { frame: 8, dx: 25, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.swordsman_3.SML03_FIGHT, [
        { direction: 1, /* E */ frames: [
            { frame: 7, dx: -19, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_1.BML01_SHOOT, [
        { direction: 2, /* SW */ frames: [
            { frame: 2, dx: -26, dy: -3 },
            { frame: 3, dx: -26, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_1.BML01_THROW_STONE, [
        { direction: 0, /* SE */ frames: [
            { frame: 14, dx: -14, dy: -1 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 10, dx: 21, dy: -1 },
            { frame: 11, dx: 21, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_2.BML02_SHOOT, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: 34, dy: -4 },
            { frame: 3, dx: 34, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_2.BML02_THROW_STONE, [
        { direction: 0, /* SE */ frames: [
            { frame: 14, dx: -15, dy: -1 },
        ] },
        { direction: 3, /* NW */ frames: [
            { frame: 18, dx: 25, dy: -2 },
            { frame: 19, dx: 25, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_3.BML03_SHOOT, [
        { direction: 2, /* SW */ frames: [
            { frame: 6, dx: -25, dy: -2 },
            { frame: 7, dx: -25, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_3.BML03_THROW_STONE, [
        { direction: 1, /* E */ frames: [
            { frame: 4, dx: -17, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.axe_warrior_1.AWL01_FIGHT, [
        { direction: 0, /* SE */ frames: [
            { frame: 17, dx: -27, dy: 3 },
        ] },
        { direction: 1, /* E */ frames: [
            { frame: 17, dx: -39, dy: -10 },
        ] },
        { direction: 3, /* NW */ frames: [
            { frame: 15, dx: -37, dy: 9 },
            { frame: 16, dx: -37, dy: 5 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 14, dx: -35, dy: 2 },
            { frame: 15, dx: -35, dy: 8 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.axe_warrior_2.AWL02_FIGHT, [
        { direction: 0, /* SE */ frames: [
            { frame: 17, dx: -27, dy: 3 },
        ] },
        { direction: 1, /* E */ frames: [
            { frame: 17, dx: -37, dy: -10 },
            { frame: 21, dx: 45, dy: -6 },
            { frame: 22, dx: 45, dy: 1 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 14, dx: -34, dy: 2 },
            { frame: 15, dx: -34, dy: 8 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.axe_warrior_3.AWL03_FIGHT, [
        { direction: 0, /* SE */ frames: [
            { frame: 17, dx: -27, dy: 3 },
        ] },
        { direction: 1, /* E */ frames: [
            { frame: 17, dx: -37, dy: -10 },
        ] },
        { direction: 2, /* SW */ frames: [
            { frame: 18, dx: -36, dy: -16 },
            { frame: 19, dx: -36, dy: -5 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 14, dx: -34, dy: 2 },
            { frame: 15, dx: -34, dy: 8 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.priest.PR_CASTSPELL, [
        { direction: 0, /* SE */ frames: [
            { frame: 19, dx: -51, dy: 4 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 10, dx: 60, dy: -5 },
            { frame: 11, dx: 60, dy: 4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.saboteur.SA_WORK_4, [
        { direction: 0, /* SE */ frames: [
            { frame: 8, dx: -15, dy: -4 },
            { frame: 9, dx: -15, dy: -4 },
            { frame: 10, dx: -15, dy: -5 },
            { frame: 11, dx: -15, dy: -5 },
            { frame: 12, dx: -15, dy: -5 },
            { frame: 13, dx: -15, dy: -4 },
            { frame: 14, dx: -15, dy: -4 },
            { frame: 15, dx: -15, dy: -5 },
            { frame: 16, dx: -15, dy: -5 },
            { frame: 17, dx: -15, dy: -4 },
            { frame: 18, dx: -15, dy: -4 },
            { frame: 19, dx: -15, dy: -3 },
            { frame: 20, dx: -16, dy: -3 },
            { frame: 21, dx: -16, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.saboteur.SA_WORK_7, [
        { direction: 2, /* SW */ frames: [
            { frame: 2, dx: -26, dy: -6 },
            { frame: 3, dx: 7, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.pioneer.P_SHOVEL, [
        { direction: 2, /* SW */ frames: [
            { frame: 10, dx: -29, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.pioneer.P_WORK, [
        { direction: 0, /* SE */ frames: [
            { frame: 6, dx: -8, dy: -4 },
            { frame: 7, dx: -8, dy: -4 },
            { frame: 8, dx: -8, dy: -5 },
            { frame: 9, dx: -8, dy: -5 },
            { frame: 10, dx: -8, dy: -4 },
            { frame: 11, dx: -8, dy: -4 },
            { frame: 12, dx: -8, dy: -4 },
            { frame: 13, dx: -8, dy: -5 },
            { frame: 14, dx: -8, dy: -5 },
            { frame: 15, dx: -8, dy: -5 },
            { frame: 16, dx: -8, dy: -5 },
            { frame: 17, dx: -8, dy: -5 },
            { frame: 18, dx: -8, dy: -3 },
            { frame: 19, dx: -8, dy: -5 },
            { frame: 20, dx: -8, dy: -4 },
            { frame: 21, dx: -8, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.thief.TH_WALK_GOOD, [
        { direction: 5, /* NE */ frames: [
            { frame: 2, dx: -11, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.thief.TH_STEAL, [
        { direction: 2, /* SW */ frames: [
            { frame: 7, dx: -33, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.geologist.G_WALK, [
        { direction: 2, /* SW */ frames: [
            { frame: 2, dx: 8, dy: -2 },
            { frame: 3, dx: 8, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.geologist.G_WORK, [
        { direction: 3, /* NW */ frames: [
            { frame: 3, dx: 30, dy: -5 },
            { frame: 21, dx: -13, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.gardener.GA_WORK, [
        { direction: 2, /* SW */ frames: [
            { frame: 11, dx: -30, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.gardener.GA_BEAT_MUSHROOM, [
        { direction: 0, /* SE */ frames: [
            { frame: 5, dx: -28, dy: 4 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 1, dx: -72, dy: 8 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.temple_servant.TS_PICKUP_WINE, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -13, dy: -3 },
            { frame: 4, dx: -13, dy: -4 },
            { frame: 5, dx: -12, dy: -4 },
            { frame: 6, dx: -13, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.donkey.DONKEY_WALK_FULLBASKET, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: 19, dy: -2 },
        ] },
    ]],
]);

/** Mayan (22.jil) */
export const FRAME_CORRECTIONS_22: ReadonlyMap<number, readonly DirectionCorrection[]> = new Map([
    [27, [ // unmapped job
        { direction: 0, /* SE */ frames: [
            { frame: 12, dx: 19, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.carrier.C_DOWN_NONE, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -8, dy: -3 },
            { frame: 3, dx: -8, dy: -4 },
            { frame: 4, dx: -8, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.carrier.C_IDLE1, [
        { direction: 0, /* SE */ frames: [
            { frame: 9, dx: -11, dy: 1 },
            { frame: 16, dx: -10, dy: 0 },
            { frame: 17, dx: -11, dy: 1 },
            { frame: 24, dx: -11, dy: 0 },
            { frame: 25, dx: -11, dy: 1 },
            { frame: 26, dx: -11, dy: 1 },
        ] },
        { direction: 1, /* E */ frames: [
            { frame: 21, dx: 18, dy: -3 },
            { frame: 22, dx: 18, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.digger.D_WORK, [
        { direction: 2, /* SW */ frames: [
            { frame: 10, dx: -41, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.builder.B_WALK, [
        { direction: 0, /* SE */ frames: [
            { frame: 10, dx: 20, dy: 0 },
            { frame: 11, dx: 20, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.builder.B_WORK, [
        { direction: 3, /* NW */ frames: [
            { frame: 2, dx: -12, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.woodcutter.WC_CUT_TREE, [
        { direction: 4, /* W */ frames: [
            { frame: 6, dx: -17, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.woodcutter.WC_PICKUP_LOG, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -12, dy: -3 },
            { frame: 3, dx: -12, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.stonecutter.ST_HACK, [
        { direction: 5, /* NE */ frames: [
            { frame: 6, dx: -14, dy: 4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.stonecutter.ST_PICKUP, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -15, dy: -4 },
            { frame: 4, dx: -15, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.forester.F_WALK, [
        { direction: 5, /* NE */ frames: [
            { frame: 11, dx: 13, dy: -2 },
            { frame: 12, dx: 13, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.forester.F_PLANT_SMALLTREE, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -7, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.farmer.FG_WALK, [
        { direction: 2, /* SW */ frames: [
            { frame: 6, dx: -15, dy: -2 },
            { frame: 7, dx: -15, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.farmer.FG_SEED_PLANTS, [
        { direction: 1, /* E */ frames: [
            { frame: 7, dx: -13, dy: -2 },
        ] },
        { direction: 3, /* NW */ frames: [
            { frame: 12, dx: 20, dy: -1 },
            { frame: 13, dx: 20, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.farmer.FG_CUT_GRAIN, [
        { direction: 0, /* SE */ frames: [
            { frame: 5, dx: -23, dy: -2 },
            { frame: 6, dx: -24, dy: -3 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 6, dx: -24, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_WALK_WATER, [
        { direction: 1, /* E */ frames: [
            { frame: 9, dx: -11, dy: -1 },
            { frame: 10, dx: -11, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_PICKUP_WATER, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -24, dy: -7 },
            { frame: 4, dx: -23, dy: -8 },
            { frame: 5, dx: -24, dy: -8 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_PICKUP_GRAIN, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -26, dy: -6 },
            { frame: 4, dx: -25, dy: -7 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_WALK_EMPTY_FOOD, [
        { direction: 0, /* SE */ frames: [
            { frame: 8, dx: 12, dy: 0 },
            { frame: 9, dx: 12, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_FEED, [
        { direction: 0, /* SE */ frames: [
            { frame: 7, dx: -18, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.fisher.FI_CATCH_FISH, [
        { direction: 0, /* SE */ frames: [
            { frame: 5, dx: -58, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.water_worker.W_WALK, [
        { direction: 3, /* NW */ frames: [
            { frame: 5, dx: 9, dy: -2 },
            { frame: 6, dx: 9, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.water_worker.W_PICKUP_WATER, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -15, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sawmill_worker.SW_WALK, [
        { direction: 1, /* E */ frames: [
            { frame: 7, dx: -9, dy: -1 },
            { frame: 8, dx: -9, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sawmill_worker.SW_PICKUP_LOG, [
        { direction: 1, /* E */ frames: [
            { frame: 8, dx: -15, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sawmill_worker.SW_PICKUP_BOARD, [
        { direction: 0, /* SE */ frames: [
            { frame: 7, dx: -9, dy: 6 },
        ] },
        { direction: 1, /* E */ frames: [
            { frame: 7, dx: -13, dy: 4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_WALK_COAL, [
        { direction: 3, /* NW */ frames: [
            { frame: 7, dx: 11, dy: -3 },
            { frame: 8, dx: 11, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_COAL, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -8, dy: -3 },
            { frame: 3, dx: -8, dy: -4 },
            { frame: 4, dx: -8, dy: -4 },
            { frame: 5, dx: -8, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_GOLDBAR, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -8, dy: -3 },
            { frame: 3, dx: -8, dy: -5 },
            { frame: 4, dx: -8, dy: -5 },
            { frame: 5, dx: -8, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_GOLDORE, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -8, dy: -3 },
            { frame: 3, dx: -8, dy: -4 },
            { frame: 4, dx: -8, dy: -4 },
            { frame: 5, dx: -8, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_IRONBAR, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -8, dy: -3 },
            { frame: 3, dx: -8, dy: -5 },
            { frame: 4, dx: -8, dy: -5 },
            { frame: 5, dx: -8, dy: -4 },
        ] },
        { direction: 1, /* E */ frames: [
            { frame: 3, dx: 19, dy: -10 },
            { frame: 4, dx: 19, dy: -8 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_WORK, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -11, dy: -3 },
            { frame: 4, dx: -12, dy: -3 },
            { frame: 5, dx: -12, dy: -3 },
            { frame: 6, dx: -12, dy: -3 },
            { frame: 7, dx: -12, dy: -3 },
            { frame: 8, dx: -12, dy: -3 },
            { frame: 9, dx: -12, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_IRONORE, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -8, dy: -3 },
            { frame: 3, dx: -8, dy: -4 },
            { frame: 4, dx: -8, dy: -6 },
            { frame: 5, dx: -8, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smith.S_WALK_COAL, [
        { direction: 2, /* SW */ frames: [
            { frame: 10, dx: -12, dy: -3 },
            { frame: 11, dx: -12, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smith.S_PICKUP_COAL, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -8, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smith.S_PICKUP_IRONBAR, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -8, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smith.S_PICKUP_STEEL, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -9, dy: -4 },
            { frame: 4, dx: -8, dy: -3 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 4, dx: 24, dy: -2 },
            { frame: 5, dx: 24, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.miller.MI_PICKUP_GRAIN, [
        { direction: 0, /* SE */ frames: [
            { frame: 10, dx: 31, dy: 0 },
            { frame: 11, dx: 31, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_WALK_FLOUR, [
        { direction: 4, /* W */ frames: [
            { frame: 4, dx: 11, dy: -1 },
            { frame: 5, dx: 11, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_WALK_DOUGH, [
        { direction: 5, /* NE */ frames: [
            { frame: 7, dx: 36, dy: -2 },
            { frame: 8, dx: 36, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_WORK_BREAD, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: -26, dy: -5 },
            { frame: 5, dx: -26, dy: -5 },
            { frame: 6, dx: -26, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_WORK_DOUGH, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: -26, dy: -5 },
            { frame: 5, dx: -26, dy: -5 },
            { frame: 6, dx: -26, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_SHOVEL_UP, [
        { direction: 2, /* SW */ frames: [
            { frame: 2, dx: -35, dy: 10 },
            { frame: 3, dx: -35, dy: 9 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_PICKUP_WATER, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: -16, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.butcher.BU_WALK_MEAT, [
        { direction: 3, /* NW */ frames: [
            { frame: 11, dx: 11, dy: -5 },
            { frame: 12, dx: 11, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.butcher.BU_PICKUP_MEAT, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -21, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.butcher.BU_PICKUP_ANIMAL, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -16, dy: -7 },
            { frame: 4, dx: -17, dy: -8 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 3, dx: -14, dy: 0 },
            { frame: 4, dx: -15, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.unknown_worker.VM_WALK, [
        { direction: 1, /* E */ frames: [
            { frame: 5, dx: 12, dy: -3 },
            { frame: 6, dx: 12, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.unknown_worker.VM_PICKUP_BOARD, [
        { direction: 4, /* W */ frames: [
            { frame: 4, dx: 28, dy: 0 },
            { frame: 5, dx: 28, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.ammunition_maker.AM_PICKUP_AMMO, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -18, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_WALK_BOARD, [
        { direction: 1, /* E */ frames: [
            { frame: 1, dx: 16, dy: -1 },
            { frame: 2, dx: 16, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_WORK, [
        { direction: 3, /* NW */ frames: [
            { frame: 2, dx: -14, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_PICKUP_IRONBAR, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -15, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_PICKUP_BOARD, [
        { direction: 2, /* SW */ frames: [
            { frame: 7, dx: -19, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_PICKUP_IRONBAR2, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -15, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.agave_farmer.AF_WALK_SMALLAGAVE, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: 23, dy: -2 },
            { frame: 5, dx: 23, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.agave_farmer.AF_PLANT_SMALLAGAVE, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -14, dy: -6 },
            { frame: 4, dx: -15, dy: -7 },
            { frame: 5, dx: -15, dy: -7 },
            { frame: 7, dx: -14, dy: -8 },
            { frame: 8, dx: -14, dy: -9 },
            { frame: 9, dx: -15, dy: -9 },
            { frame: 15, dx: -14, dy: -9 },
            { frame: 16, dx: -14, dy: -9 },
            { frame: 17, dx: -14, dy: -9 },
            { frame: 18, dx: -14, dy: -9 },
            { frame: 19, dx: -14, dy: -8 },
            { frame: 20, dx: -15, dy: -7 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.agave_farmer.AF_WORK_MACHETE, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -6, dy: -6 },
        ] },
        { direction: 2, /* SW */ frames: [
            { frame: 8, dx: -26, dy: -1 },
            { frame: 9, dx: -26, dy: 3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.agave_farmer.AF_PICKUP_AGAVE, [
        { direction: 4, /* W */ frames: [
            { frame: 5, dx: -25, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.tequila_maker.TM_WALK_AGAVE, [
        { direction: 5, /* NE */ frames: [
            { frame: 1, dx: -14, dy: -3 },
            { frame: 2, dx: -14, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.tequila_maker.TM_PICKUP_WATER, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -20, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.swordsman_3.SML03_WALK, [
        { direction: 5, /* NE */ frames: [
            { frame: 1, dx: -18, dy: -1 },
            { frame: 2, dx: -18, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_1.BML01_SHOOT, [
        { direction: 4, /* W */ frames: [
            { frame: 4, dx: 37, dy: 0 },
            { frame: 5, dx: 37, dy: 3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_1.BML01_THROW_STONE, [
        { direction: 1, /* E */ frames: [
            { frame: 4, dx: -23, dy: -6 },
            { frame: 5, dx: -23, dy: -7 },
            { frame: 6, dx: -23, dy: -7 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_2.BML02_SHOOT, [
        { direction: 2, /* SW */ frames: [
            { frame: 6, dx: 30, dy: -2 },
            { frame: 7, dx: 30, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_2.BML02_THROW_STONE, [
        { direction: 1, /* E */ frames: [
            { frame: 4, dx: -30, dy: -8 },
            { frame: 5, dx: -30, dy: -9 },
            { frame: 6, dx: -30, dy: -9 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 10, dx: 39, dy: -6 },
            { frame: 11, dx: 39, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_3.BML03_WALK, [
        { direction: 2, /* SW */ frames: [
            { frame: 10, dx: -8, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_3.BML03_SHOOT, [
        { direction: 3, /* NW */ frames: [
            { frame: 16, dx: -15, dy: -2 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 2, dx: 37, dy: 0 },
            { frame: 3, dx: 37, dy: 5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_3.BML03_THROW_STONE, [
        { direction: 1, /* E */ frames: [
            { frame: 4, dx: -32, dy: -9 },
            { frame: 5, dx: -32, dy: -10 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_3.BML03_FIGHT, [
        { direction: 1, /* E */ frames: [
            { frame: 11, dx: -26, dy: -4 },
            { frame: 12, dx: -26, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.blowgun_warrior_1.BGWL01_FIGHT, [
        { direction: 4, /* W */ frames: [
            { frame: 24, dx: 53, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.blowgun_warrior_2.BGWL02_FIGHT, [
        { direction: 2, /* SW */ frames: [
            { frame: 24, dx: 42, dy: -2 },
        ] },
    ]],
    [280, [ // unmapped job
        { direction: 4, /* W */ frames: [
            { frame: 2, dx: -7, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.blowgun_warrior_3.BGWL03_FIGHT, [
        { direction: 0, /* SE */ frames: [
            { frame: 24, dx: 43, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.squad_leader.SQL_FIGHT, [
        { direction: 3, /* NW */ frames: [
            { frame: 10, dx: 23, dy: -3 },
            { frame: 11, dx: 23, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.priest.PR_WALK, [
        { direction: 1, /* E */ frames: [
            { frame: 7, dx: -17, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.priest.PR_CASTSPELL, [
        { direction: 2, /* SW */ frames: [
            { frame: 12, dx: 61, dy: 5 },
            { frame: 13, dx: 61, dy: 11 },
            { frame: 22, dx: 59, dy: -13 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 22, dx: 66, dy: -10 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.saboteur.SA_WORK_3, [
        { direction: 0, /* SE */ frames: [
            { frame: 12, dx: -17, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.saboteur.SA_WORK_4, [
        { direction: 0, /* SE */ frames: [
            { frame: 21, dx: -15, dy: -4 },
            { frame: 22, dx: -15, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.pioneer.P_WORK, [
        { direction: 0, /* SE */ frames: [
            { frame: 20, dx: -8, dy: -5 },
        ] },
        { direction: 3, /* NW */ frames: [
            { frame: 3, dx: 20, dy: -5 },
            { frame: 4, dx: 20, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.thief.TH_STEAL, [
        { direction: 1, /* E */ frames: [
            { frame: 6, dx: 32, dy: -1 },
            { frame: 7, dx: 32, dy: 5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.thief.TH_DROP_GOOD, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -9, dy: -2 },
            { frame: 4, dx: -8, dy: -2 },
            { frame: 5, dx: -8, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.geologist.G_WALK, [
        { direction: 5, /* NE */ frames: [
            { frame: 3, dx: 10, dy: -5 },
            { frame: 4, dx: 10, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.geologist.G_SEARCH, [
        { direction: 0, /* SE */ frames: [
            { frame: 18, dx: -24, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.geologist.G_WORK, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: -22, dy: -5 },
            { frame: 6, dx: -22, dy: -5 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 4, dx: 31, dy: -4 },
            { frame: 5, dx: 31, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.gardener.GA_WORK, [
        { direction: 2, /* SW */ frames: [
            { frame: 10, dx: -34, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.gardener.GA_BEAT_MUSHROOM, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: -23, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.temple_servant.TS_WALK, [
        { direction: 0, /* SE */ frames: [
            { frame: 10, dx: 9, dy: -3 },
            { frame: 11, dx: 9, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.temple_servant.TS_PICKUP_WINE, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: -26, dy: -8 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.temple_servant.TS_WORK, [
        { direction: 0, /* SE */ frames: [
            { frame: 6, dx: -10, dy: 0 },
            { frame: 7, dx: -10, dy: 1 },
        ] },
    ]],
]);

/** DarkTribe (23.jil) */
export const FRAME_CORRECTIONS_23: ReadonlyMap<number, readonly DirectionCorrection[]> = new Map([
    [SETTLER_JOB_INDICES.swordsman_1.SML01_FIGHT, [
        { direction: 0, /* SE */ frames: [
            { frame: 6, dx: -15, dy: 2 },
            { frame: 7, dx: -13, dy: 0 },
            { frame: 8, dx: -13, dy: 0 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 5, dx: -47, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_1.BML01_SHOOT, [
        { direction: 3, /* NW */ frames: [
            { frame: 13, dx: -40, dy: 3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.dark_gardener.DG_SEED, [
        { direction: 4, /* W */ frames: [
            { frame: 9, dx: -33, dy: -1 },
            { frame: 10, dx: -33, dy: -2 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 11, dx: -19, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.mushroom_farmer.MF_PLANT, [
        { direction: 0, /* SE */ frames: [
            { frame: 21, dx: -12, dy: -5 },
            { frame: 22, dx: -12, dy: -4 },
        ] },
        { direction: 2, /* SW */ frames: [
            { frame: 20, dx: 23, dy: -15 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 1, dx: 23, dy: 1 },
            { frame: 21, dx: 23, dy: -2 },
            { frame: 23, dx: 23, dy: 0 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 1, dx: 24, dy: 0 },
            { frame: 23, dx: 24, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.mushroom_farmer.MF_FIGHT, [
        { direction: 3, /* NW */ frames: [
            { frame: 1, dx: -39, dy: 0 },
            { frame: 3, dx: -39, dy: -2 },
            { frame: 9, dx: -39, dy: -2 },
            { frame: 10, dx: -39, dy: 0 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 4, dx: -37, dy: -2 },
            { frame: 8, dx: -37, dy: -2 },
        ] },
    ]],
    [322, [ // unmapped job
        { direction: 3, /* NW */ frames: [
            { frame: 1, dx: -39, dy: 0 },
            { frame: 3, dx: -39, dy: -2 },
            { frame: 9, dx: -39, dy: -2 },
            { frame: 10, dx: -39, dy: 0 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 4, dx: -37, dy: -2 },
            { frame: 8, dx: -37, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shaman.SHM_ENSLAVE, [
        { direction: 0, /* SE */ frames: [
            { frame: 7, dx: -25, dy: -2 },
            { frame: 8, dx: -25, dy: -2 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 6, dx: 47, dy: 4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.slaved_settler.SS_POLISH, [
        { direction: 4, /* W */ frames: [
            { frame: 10, dx: -29, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.angel_1.ANGEL1_WALK, [
        { direction: 2, /* SW */ frames: [
            { frame: 7, dx: -8, dy: 76 },
            { frame: 11, dx: -10, dy: 140 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.angel_2.ANGEL2_WALK, [
        { direction: 2, /* SW */ frames: [
            { frame: 7, dx: -8, dy: 76 },
            { frame: 11, dx: -10, dy: 140 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.angel_3.ANGEL3_WALK, [
        { direction: 2, /* SW */ frames: [
            { frame: 7, dx: -8, dy: 76 },
            { frame: 11, dx: -10, dy: 140 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.manacopter_master.MC_FIGHT, [
        { direction: 0, /* SE */ frames: [
            { frame: 5, dx: 49, dy: -1 },
            { frame: 6, dx: -39, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.manacopter_master.MC_WORK, [
        { direction: 4, /* W */ frames: [
            { frame: 5, dx: 23, dy: 0 },
            { frame: 6, dx: 23, dy: 0 },
            { frame: 9, dx: 23, dy: 0 },
            { frame: 10, dx: 23, dy: 0 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 7, dx: -22, dy: 4 },
            { frame: 9, dx: -22, dy: 4 },
        ] },
    ]],
]);

/** Trojan (24.jil) */
export const FRAME_CORRECTIONS_24: ReadonlyMap<number, readonly DirectionCorrection[]> = new Map([
    [14, [ // unmapped job
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: 23, dy: -1 },
        ] },
    ]],
    [23, [ // unmapped job
        { direction: 5, /* NE */ frames: [
            { frame: 3, dx: 19, dy: 0 },
            { frame: 4, dx: 19, dy: 0 },
        ] },
    ]],
    [27, [ // unmapped job
        { direction: 0, /* SE */ frames: [
            { frame: 12, dx: 17, dy: -1 },
        ] },
    ]],
    [41, [ // unmapped job
        { direction: 1, /* E */ frames: [
            { frame: 9, dx: -16, dy: -1 },
            { frame: 10, dx: -16, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.carrier.C_DOWN_NONE, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -11, dy: -4 },
            { frame: 3, dx: -11, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.carrier.C_IDLE1, [
        { direction: 0, /* SE */ frames: [
            { frame: 20, dx: 27, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.carrier.C_IDLE2, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -10, dy: -3 },
            { frame: 4, dx: -10, dy: -3 },
        ] },
        { direction: 1, /* E */ frames: [
            { frame: 6, dx: -13, dy: -1 },
            { frame: 8, dx: -12, dy: 1 },
        ] },
        { direction: 2, /* SW */ frames: [
            { frame: 28, dx: 12, dy: 0 },
            { frame: 29, dx: 12, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.carrier.C_STRIKE1, [
        { direction: 5, /* NE */ frames: [
            { frame: 14, dx: -22, dy: 7 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.digger.D_WORK, [
        { direction: 2, /* SW */ frames: [
            { frame: 10, dx: -34, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.builder.B_WORK, [
        { direction: 2, /* SW */ frames: [
            { frame: 3, dx: -11, dy: -2 },
        ] },
        { direction: 3, /* NW */ frames: [
            { frame: 2, dx: -13, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.woodcutter.WC_WALK, [
        { direction: 0, /* SE */ frames: [
            { frame: 6, dx: 8, dy: -1 },
            { frame: 7, dx: 8, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.woodcutter.WC_PICKUP_LOG, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: -19, dy: -4 },
        ] },
        { direction: 1, /* E */ frames: [
            { frame: 8, dx: -23, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.stonecutter.ST_HACK, [
        { direction: 5, /* NE */ frames: [
            { frame: 7, dx: -9, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.stonecutter.ST_PICKUP, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -19, dy: -4 },
            { frame: 4, dx: -19, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.forester.F_PLANT_SMALLTREE, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: -13, dy: -7 },
        ] },
        { direction: 1, /* E */ frames: [
            { frame: 11, dx: 35, dy: -15 },
            { frame: 12, dx: 35, dy: -13 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.farmer.FG_WALK_GRAIN, [
        { direction: 4, /* W */ frames: [
            { frame: 12, dx: -17, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.farmer.FG_CUT_GRAIN, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -10, dy: -1 },
        ] },
        { direction: 2, /* SW */ frames: [
            { frame: 7, dx: -10, dy: 1 },
        ] },
        { direction: 3, /* NW */ frames: [
            { frame: 7, dx: -9, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.farmer.FG_PICKUP_GRAIN, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: -15, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_WALK_GRAIN, [
        { direction: 5, /* NE */ frames: [
            { frame: 1, dx: 20, dy: -1 },
            { frame: 2, dx: 20, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_PICKUP_WATER, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -19, dy: -5 },
            { frame: 4, dx: -19, dy: -7 },
            { frame: 5, dx: -19, dy: -6 },
            { frame: 6, dx: -18, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_PICKUP_GRAIN, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -20, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_WALK_FULL_FOOD, [
        { direction: 4, /* W */ frames: [
            { frame: 6, dx: 13, dy: -1 },
            { frame: 7, dx: 13, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.animal_farmer.FA_FEED, [
        { direction: 0, /* SE */ frames: [
            { frame: 7, dx: -17, dy: 1 },
            { frame: 8, dx: -17, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.fisher.FI_CATCH_FISH, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -47, dy: -2 },
            { frame: 3, dx: -47, dy: 2 },
            { frame: 4, dx: -47, dy: 1 },
            { frame: 5, dx: -45, dy: 1 },
        ] },
        { direction: 1, /* E */ frames: [
            { frame: 4, dx: -43, dy: -11 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.fisher.FI_PICKUP_FISH, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -9, dy: -3 },
            { frame: 3, dx: -10, dy: -4 },
            { frame: 4, dx: -10, dy: -3 },
            { frame: 5, dx: -9, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.water_worker.W_WALK_EMPTY_WATER, [
        { direction: 3, /* NW */ frames: [
            { frame: 4, dx: -8, dy: 0 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 4, dx: -9, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.water_worker.W_WALK_FULL_WATER, [
        { direction: 5, /* NE */ frames: [
            { frame: 5, dx: 13, dy: -2 },
            { frame: 6, dx: 13, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.water_worker.W_PICKUP_WATER, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -17, dy: -6 },
            { frame: 4, dx: -17, dy: -7 },
            { frame: 5, dx: -17, dy: -7 },
            { frame: 6, dx: -16, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sawmill_worker.SW_WALK_BOARD, [
        { direction: 5, /* NE */ frames: [
            { frame: 5, dx: 12, dy: -2 },
            { frame: 6, dx: 12, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sawmill_worker.SW_PICKUP_LOG, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -11, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sawmill_worker.SW_PICKUP_BOARD, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -17, dy: -5 },
        ] },
        { direction: 1, /* E */ frames: [
            { frame: 8, dx: -19, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_WALK, [
        { direction: 2, /* SW */ frames: [
            { frame: 12, dx: 8, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_WALK_GOLDORE, [
        { direction: 4, /* W */ frames: [
            { frame: 8, dx: 13, dy: -2 },
            { frame: 9, dx: 13, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_COAL, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -12, dy: -4 },
            { frame: 3, dx: -13, dy: -6 },
            { frame: 4, dx: -13, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_GOLDBAR, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -13, dy: -4 },
            { frame: 3, dx: -13, dy: -5 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 2, dx: 20, dy: 0 },
            { frame: 3, dx: 20, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_GOLDORE, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -12, dy: -4 },
            { frame: 3, dx: -13, dy: -6 },
            { frame: 4, dx: -13, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_IRONBAR, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -13, dy: -4 },
            { frame: 3, dx: -13, dy: -5 },
            { frame: 4, dx: -12, dy: -8 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_WORK, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: -13, dy: -3 },
            { frame: 5, dx: -14, dy: -3 },
            { frame: 6, dx: -13, dy: -3 },
            { frame: 7, dx: -13, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smelter.SME_PICKUP_IRONORE, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -12, dy: -4 },
            { frame: 3, dx: -13, dy: -6 },
            { frame: 4, dx: -13, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smith.S_WALK, [
        { direction: 4, /* W */ frames: [
            { frame: 4, dx: 16, dy: -2 },
            { frame: 5, dx: 16, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smith.S_COOL_STEEL, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -9, dy: -1 },
            { frame: 4, dx: -9, dy: -1 },
            { frame: 5, dx: -9, dy: -1 },
            { frame: 12, dx: -9, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smith.S_PICKUP_COAL, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -8, dy: -4 },
            { frame: 3, dx: -8, dy: -5 },
            { frame: 4, dx: -8, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smith.S_PICKUP_IRONBAR, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -8, dy: -4 },
            { frame: 3, dx: -8, dy: -5 },
            { frame: 4, dx: -8, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.smith.S_PICKUP_STEEL, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -14, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.miller.MI_WALK_FLOUR, [
        { direction: 1, /* E */ frames: [
            { frame: 7, dx: 8, dy: -2 },
            { frame: 8, dx: 8, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.miller.MI_PICKUP_GRAIN, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -12, dy: -4 },
            { frame: 3, dx: -12, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.miller.MI_PICKUP_FLOUR, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -12, dy: -3 },
            { frame: 3, dx: -12, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_WALK_DOUGH, [
        { direction: 3, /* NW */ frames: [
            { frame: 7, dx: -34, dy: -1 },
            { frame: 8, dx: -34, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_WALK_WATER, [
        { direction: 2, /* SW */ frames: [
            { frame: 8, dx: -8, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_WORK_BREAD, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -10, dy: 0 },
            { frame: 3, dx: -10, dy: 0 },
            { frame: 4, dx: -10, dy: 0 },
            { frame: 5, dx: -10, dy: 0 },
            { frame: 6, dx: -9, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_WORK_DOUGH, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -10, dy: 0 },
            { frame: 3, dx: -10, dy: 0 },
            { frame: 4, dx: -10, dy: 0 },
            { frame: 5, dx: -10, dy: 0 },
            { frame: 6, dx: -9, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_PICKUP_WATER, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -12, dy: -5 },
            { frame: 3, dx: -12, dy: -6 },
            { frame: 4, dx: -12, dy: -6 },
            { frame: 5, dx: -12, dy: -5 },
        ] },
        { direction: 3, /* NW */ frames: [
            { frame: 2, dx: 23, dy: -5 },
            { frame: 3, dx: 23, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.baker.BA_PICKUP_FLOUR, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -13, dy: -4 },
            { frame: 3, dx: -12, dy: -7 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.butcher.BU_WALK_ANIMAL, [
        { direction: 2, /* SW */ frames: [
            { frame: 4, dx: -16, dy: -4 },
            { frame: 5, dx: -16, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.unknown_worker.VM_PICKUP_BOARD, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -19, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.unknown_worker.VM_PICKUP_IRONBAR, [
        { direction: 0, /* SE */ frames: [
            { frame: 2, dx: -12, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.unknown_worker.VM_WORK, [
        { direction: 3, /* NW */ frames: [
            { frame: 2, dx: 14, dy: -4 },
            { frame: 3, dx: 14, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.ammunition_maker.AM_WALK, [
        { direction: 4, /* W */ frames: [
            { frame: 2, dx: 10, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.ammunition_maker.AM_WALK_THIRDGOOD, [
        { direction: 5, /* NE */ frames: [
            { frame: 11, dx: 18, dy: -1 },
            { frame: 12, dx: 18, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.ammunition_maker.AM_PICKUP_FIRSTGOOD, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -15, dy: -5 },
            { frame: 4, dx: -16, dy: -6 },
            { frame: 5, dx: -16, dy: -6 },
            { frame: 6, dx: -15, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.ammunition_maker.AM_PICKUP_SECONDGOOD, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -15, dy: -5 },
            { frame: 4, dx: -16, dy: -6 },
            { frame: 5, dx: -16, dy: -6 },
            { frame: 6, dx: -15, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.ammunition_maker.AM_PICKUP_THIRDGOOD, [
        { direction: 5, /* NE */ frames: [
            { frame: 6, dx: -27, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.ammunition_maker.AM_PICKUP_AMMO, [
        { direction: 1, /* E */ frames: [
            { frame: 5, dx: 27, dy: -17 },
            { frame: 6, dx: 27, dy: -13 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_WALK_IRONBAR2, [
        { direction: 4, /* W */ frames: [
            { frame: 8, dx: 17, dy: -1 },
            { frame: 9, dx: 17, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_WORK, [
        { direction: 2, /* SW */ frames: [
            { frame: 4, dx: -10, dy: -2 },
        ] },
        { direction: 3, /* NW */ frames: [
            { frame: 3, dx: -13, dy: -2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_PICKUP_IRONBAR, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -22, dy: -6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_PICKUP_BOARD, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -22, dy: -6 },
        ] },
        { direction: 3, /* NW */ frames: [
            { frame: 1, dx: 25, dy: -1 },
            { frame: 2, dx: 25, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.shipyard_worker.SYW_PICKUP_IRONBAR2, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -22, dy: -6 },
        ] },
    ]],
    [229, [ // unmapped job
        { direction: 1, /* E */ frames: [
            { frame: 7, dx: 24, dy: -3 },
            { frame: 8, dx: 24, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.swordsman_3.SML03_WALK, [
        { direction: 3, /* NW */ frames: [
            { frame: 3, dx: -10, dy: -5 },
            { frame: 4, dx: -10, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_1.BML01_SHOOT, [
        { direction: 3, /* NW */ frames: [
            { frame: 4, dx: -35, dy: -1 },
            { frame: 5, dx: -35, dy: 3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_1.BML01_FIGHT, [
        { direction: 0, /* SE */ frames: [
            { frame: 8, dx: 32, dy: -2 },
            { frame: 9, dx: 32, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_2.BML02_SHOOT, [
        { direction: 1, /* E */ frames: [
            { frame: 16, dx: 35, dy: 3 },
            { frame: 17, dx: 35, dy: 6 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_2.BML02_THROW_STONE, [
        { direction: 5, /* NE */ frames: [
            { frame: 4, dx: 43, dy: -2 },
            { frame: 5, dx: 43, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.bowman_3.BML03_SHOOT, [
        { direction: 4, /* W */ frames: [
            { frame: 2, dx: 34, dy: 0 },
            { frame: 3, dx: 34, dy: 4 },
        ] },
    ]],
    [286, [ // unmapped job
        { direction: 4, /* W */ frames: [
            { frame: 12, dx: -20, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.saboteur.SA_WALK, [
        { direction: 5, /* NE */ frames: [
            { frame: 9, dx: -8, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.pioneer.P_WALK, [
        { direction: 2, /* SW */ frames: [
            { frame: 4, dx: -15, dy: -4 },
            { frame: 5, dx: -15, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.pioneer.P_SHOVEL, [
        { direction: 2, /* SW */ frames: [
            { frame: 10, dx: -35, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.pioneer.P_WORK, [
        { direction: 0, /* SE */ frames: [
            { frame: 20, dx: -13, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.thief.TH_STEAL, [
        { direction: 4, /* W */ frames: [
            { frame: 4, dx: 39, dy: -1 },
            { frame: 5, dx: 39, dy: 4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.thief.TH_DROP_GOOD, [
        { direction: 1, /* E */ frames: [
            { frame: 4, dx: -8, dy: -8 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.geologist.G_SEARCH, [
        { direction: 0, /* SE */ frames: [
            { frame: 18, dx: -14, dy: -2 },
            { frame: 20, dx: -14, dy: -2 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 11, dx: -10, dy: 2 },
            { frame: 12, dx: -10, dy: 4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.geologist.G_WORK, [
        { direction: 3, /* NW */ frames: [
            { frame: 22, dx: -39, dy: 0 },
        ] },
        { direction: 4, /* W */ frames: [
            { frame: 12, dx: 51, dy: -1 },
            { frame: 13, dx: 51, dy: 5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.gardener.GA_WALK, [
        { direction: 2, /* SW */ frames: [
            { frame: 2, dx: -13, dy: -4 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.gardener.GA_WORK, [
        { direction: 2, /* SW */ frames: [
            { frame: 11, dx: -38, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.gardener.GA_BEAT_MUSHROOM, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: -21, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.temple_servant.TS_WALK, [
        { direction: 1, /* E */ frames: [
            { frame: 1, dx: 14, dy: -3 },
            { frame: 2, dx: 14, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.temple_servant.TS_PICKUP_WINE, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -21, dy: -5 },
            { frame: 4, dx: -20, dy: -7 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.temple_servant.TS_WORK, [
        { direction: 2, /* SW */ frames: [
            { frame: 16, dx: -29, dy: -4 },
            { frame: 17, dx: -29, dy: 1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.temple_servant.TS_ANIM, [
        { direction: 0, /* SE */ frames: [
            { frame: 6, dx: -15, dy: -5 },
            { frame: 17, dx: -13, dy: -1 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.donkey.DONKEY_WALK, [
        { direction: 0, /* SE */ frames: [
            { frame: 7, dx: 19, dy: -3 },
            { frame: 8, dx: 19, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.donkey.DONKEY_WALK_EMPTYBASKET, [
        { direction: 2, /* SW */ frames: [
            { frame: 3, dx: -19, dy: -2 },
            { frame: 4, dx: -19, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.catapultist_1.BCL01_FIGHT, [
        { direction: 0, /* SE */ frames: [
            { frame: 18, dx: -29, dy: 0 },
        ] },
        { direction: 2, /* SW */ frames: [
            { frame: 19, dx: 24, dy: -10 },
            { frame: 20, dx: 24, dy: -3 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.catapultist_3.BCL03_FIGHT, [
        { direction: 1, /* E */ frames: [
            { frame: 17, dx: -40, dy: -12 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 17, dx: -33, dy: 14 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sunflower_farmer.SFF_WALK, [
        { direction: 4, /* W */ frames: [
            { frame: 5, dx: 10, dy: -2 },
            { frame: 6, dx: 10, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sunflower_farmer.SFF_WALK_PLANT, [
        { direction: 3, /* NW */ frames: [
            { frame: 6, dx: -11, dy: -7 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sunflower_farmer.SFF_WORK_PLANT, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -10, dy: -5 },
            { frame: 4, dx: -10, dy: -6 },
            { frame: 5, dx: -10, dy: -6 },
            { frame: 7, dx: -10, dy: -7 },
            { frame: 8, dx: -10, dy: -8 },
            { frame: 9, dx: -10, dy: -8 },
            { frame: 10, dx: -10, dy: -8 },
            { frame: 11, dx: -9, dy: -8 },
            { frame: 12, dx: -9, dy: -8 },
            { frame: 19, dx: -10, dy: -8 },
            { frame: 20, dx: -10, dy: -7 },
            { frame: 21, dx: -11, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sunflower_farmer.SFF_WORK, [
        { direction: 0, /* SE */ frames: [
            { frame: 7, dx: -23, dy: 0 },
            { frame: 8, dx: -23, dy: 0 },
            { frame: 9, dx: -23, dy: 0 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sunflower_farmer.SFF_PICKUP_PLANT, [
        { direction: 2, /* SW */ frames: [
            { frame: 3, dx: 38, dy: -6 },
            { frame: 4, dx: 38, dy: 0 },
        ] },
        { direction: 5, /* NE */ frames: [
            { frame: 11, dx: -29, dy: -5 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.sunflower_farmer.SFF_PICKUP_SUNFLOWER, [
        { direction: 0, /* SE */ frames: [
            { frame: 4, dx: -17, dy: -8 },
            { frame: 5, dx: -17, dy: -8 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.oil_maker.SOM_WALK_OIL, [
        { direction: 5, /* NE */ frames: [
            { frame: 10, dx: 13, dy: -2 },
            { frame: 11, dx: 13, dy: 2 },
        ] },
    ]],
    [SETTLER_JOB_INDICES.oil_maker.SOM_PICKUP_PLANT, [
        { direction: 0, /* SE */ frames: [
            { frame: 3, dx: -17, dy: -5 },
            { frame: 4, dx: -18, dy: -7 },
            { frame: 5, dx: -18, dy: -7 },
            { frame: 6, dx: -16, dy: -7 },
        ] },
    ]],
]);

/** All correction maps indexed by GFX file number. */
export const CORRECTIONS_BY_FILE = new Map<number, ReadonlyMap<number, readonly DirectionCorrection[]>>([
    [20, FRAME_CORRECTIONS_20],
    [21, FRAME_CORRECTIONS_21],
    [22, FRAME_CORRECTIONS_22],
    [23, FRAME_CORRECTIONS_23],
    [24, FRAME_CORRECTIONS_24],
]);